### ISSUE TITLE
Implement cross-validation for smoothness tuning parameter

### ISSUE THREAD

**Issue by HeejongBong** [shamindras/bradley-terry-convexopt#26]
## Todo list
- [ ] decide if the remained data guarantee the existence of solutions
- [ ] decide if the remained data guarantee the uniqueness of solutions
- [x] implement cross validation
