### ISSUE TITLE
Initial implementation of Proximal Gradient Method

### ISSUE THREAD

**Issue by HeejongBong** [shamindras/bradley-terry-convexopt#5]
## Todo list
- [x] get proximal operator for L2-penalty
- [x] get proximal operator for L1-penalty
- [x] implement proximal gradient method
- [x] implement backtracking line search
- [x] implement acceleration
